### ISSUE TITLE
You can die in a Replay but pass the map ingame

### ISSUE THREAD

**Issue by Veeyu22** [Quaver/Quaver.API#135] opened 2022-09-07 01:38 UTC
**Bug occurs at ~2:08, I 'die'. But this score is submitted and I passed the map in-game.**
**[Veeyu - Gram - Nibelungen - Mythology.zip](https://github.com/Quaver/Quaver.API/files/9501944/Veeyu.-.Gram.-.Nibelungen.-.Mythology.zip)**
https://quavergame.com/user/300350 (my uuid)

**Comment by Reihynn** [comment] 2022-09-07 06:15
duplicate of https://github.com/Quaver/Quaver/issues/3518 (?) i guess

**Closed** 2022-09-07 06:25 UTC
